"use client";

import { useEffect, useState } from "react";
import { Bell, CalendarCheck, CreditCard, Megaphone, WalletCards } from "lucide-react";
import { DashboardPageHeader } from "@/components/dashboard/dashboard-page-header";
import { Button } from "@/components/ui/button";
import { useDemoSession } from "@/hooks/use-demo-session";
import { getDemoNotifications, markAllNotificationsRead } from "@/services/demo-storage";
import type { DemoNotificationRecord } from "@/types/demo";

const icons = { booking: CalendarCheck, membership: WalletCards, payment: CreditCard, studio: Megaphone };

export function NotificationsView() {
  const { session } = useDemoSession();
  const [items, setItems] = useState<DemoNotificationRecord[]>([]);
  useEffect(() => { const load = () => { if (session) setItems(getDemoNotifications(session.id)); }; load(); window.addEventListener("ananda-demo-change", load); return () => window.removeEventListener("ananda-demo-change", load); }, [session]);
  const unread = items.filter((item) => !item.read).length;
  return <><DashboardPageHeader eyebrow="Notifications" title="Studio updates." copy="Booking, payment and membership updates generated by your demo activity." action={unread > 0 && session ? <Button variant="outline" className="rounded-full bg-white" onClick={() => markAllNotificationsRead(session.id)}>Mark all read</Button> : undefined} />
    <div className="overflow-hidden rounded-[1.5rem] border border-[#17362d]/10 bg-white">{items.length ? items.map((item) => { const Icon = icons[item.category]; return <article key={item.id} className={`flex gap-4 border-b border-[#17362d]/10 p-5 last:border-0 sm:p-6 ${item.read ? "bg-white" : "bg-[#f3f6f1]"}`}><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[#e8ede6] text-[#a65f3d]"><Icon className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><h2 className="font-semibold">{item.title}</h2>{!item.read && <span className="mt-1 size-2 shrink-0 rounded-full bg-[#a65f3d]" aria-label="Unread" />}</div><p className="mt-1 text-sm leading-6 text-[#65756e]">{item.body}</p><p className="mt-2 text-xs text-[#87938d]">{new Date(item.createdAt).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</p></div></article>; }) : <div className="p-10 text-center"><Bell className="mx-auto size-7 text-[#a65f3d]" /><h2 className="mt-4 font-display text-3xl">You’re all caught up.</h2><p className="mt-2 text-sm text-[#65756e]">New demo activity will appear here.</p></div>}</div>
    <p className="mt-5 text-xs text-[#738078]">WhatsApp and email notifications remain simulated; nothing is sent outside this browser.</p></>;
}
